package defpackage;

import com.sggc.fongmi.mobile.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class gn3 {
    public static int A = 15;
    public static int B = 16;
    public static int C = 17;
    public static int D = 18;
    public static int E = 19;
    public static int F = 20;
    public static int G = 26;
    public static int H = 27;
    public static int I = 28;
    public static int J = 29;
    public static int K = 30;
    public static int L = 31;
    public static int M = 32;
    public static int N = 33;
    public static int O = 34;
    public static int P = 35;
    public static int Q = 36;
    public static int R = 37;
    public static int S = 38;
    public static int T = 39;
    public static int U = 42;
    public static int W = 3;
    public static int X = 4;
    public static int Y = 9;
    public static int Z = 13;
    public static int a0 = 14;
    public static int b = 0;
    public static int b0 = 15;
    public static int c0 = 16;
    public static int d = 0;
    public static int d0 = 22;
    public static int e = 1;
    public static int e0 = 28;
    public static int f = 2;
    public static int f0 = 35;
    public static int g = 3;
    public static int g0 = 38;
    public static int h = 4;
    public static int h0 = 42;
    public static int i = 5;
    public static int i0 = 45;
    public static int j = 6;
    public static int j0 = 50;
    public static int k = 7;
    public static int k0 = 51;
    public static int l = 8;
    public static int m = 9;
    public static int n = 10;
    public static int o = 11;
    public static int p = 12;
    public static int q = 13;
    public static int s = 2;
    public static int t = 6;
    public static int u = 7;
    public static int v = 8;
    public static int w = 9;
    public static int x = 10;
    public static int y = 11;
    public static int z = 12;
    public static int[] a = {R.attr.resize_mode};
    public static int[] c = {R.attr.ad_marker_color, R.attr.ad_marker_width, R.attr.bar_gravity, R.attr.bar_height, R.attr.buffered_color, R.attr.played_ad_marker_color, R.attr.played_color, R.attr.scrubber_color, R.attr.scrubber_disabled_size, R.attr.scrubber_dragged_size, R.attr.scrubber_drawable, R.attr.scrubber_enabled_size, R.attr.touch_target_height, R.attr.unplayed_color};
    public static int[] r = {R.attr.ad_marker_color, R.attr.ad_marker_width, R.attr.animation_enabled, R.attr.bar_gravity, R.attr.bar_height, R.attr.buffered_color, R.attr.controller_layout_id, R.attr.fastforward_icon, R.attr.fullscreen_enter_icon, R.attr.fullscreen_exit_icon, R.attr.next_icon, R.attr.pause_icon, R.attr.play_icon, R.attr.played_ad_marker_color, R.attr.played_color, R.attr.previous_icon, R.attr.repeat_all_icon, R.attr.repeat_off_icon, R.attr.repeat_one_icon, R.attr.repeat_toggle_modes, R.attr.rewind_icon, R.attr.scrubber_color, R.attr.scrubber_disabled_size, R.attr.scrubber_dragged_size, R.attr.scrubber_drawable, R.attr.scrubber_enabled_size, R.attr.show_fastforward_button, R.attr.show_next_button, R.attr.show_previous_button, R.attr.show_rewind_button, R.attr.show_shuffle_button, R.attr.show_subtitle_button, R.attr.show_timeout, R.attr.show_vr_button, R.attr.shuffle_off_icon, R.attr.shuffle_on_icon, R.attr.subtitle_off_icon, R.attr.subtitle_on_icon, R.attr.time_bar_min_update_interval, R.attr.time_bar_scrubbing_enabled, R.attr.touch_target_height, R.attr.unplayed_color, R.attr.vr_icon};
    public static int[] V = {R.attr.ad_marker_color, R.attr.ad_marker_width, R.attr.animation_enabled, R.attr.artwork_display_mode, R.attr.auto_show, R.attr.bar_gravity, R.attr.bar_height, R.attr.buffered_color, R.attr.controller_layout_id, R.attr.default_artwork, R.attr.fastforward_icon, R.attr.fullscreen_enter_icon, R.attr.fullscreen_exit_icon, R.attr.hide_during_ads, R.attr.hide_on_touch, R.attr.image_display_mode, R.attr.keep_content_on_player_reset, R.attr.next_icon, R.attr.pause_icon, R.attr.play_icon, R.attr.played_ad_marker_color, R.attr.played_color, R.attr.player_layout_id, R.attr.previous_icon, R.attr.repeat_all_icon, R.attr.repeat_off_icon, R.attr.repeat_one_icon, R.attr.repeat_toggle_modes, R.attr.resize_mode, R.attr.rewind_icon, R.attr.scrubber_color, R.attr.scrubber_disabled_size, R.attr.scrubber_dragged_size, R.attr.scrubber_drawable, R.attr.scrubber_enabled_size, R.attr.show_buffering, R.attr.show_shuffle_button, R.attr.show_subtitle_button, R.attr.show_timeout, R.attr.show_vr_button, R.attr.shuffle_off_icon, R.attr.shuffle_on_icon, R.attr.shutter_background_color, R.attr.subtitle_off_icon, R.attr.subtitle_on_icon, R.attr.surface_type, R.attr.time_bar_min_update_interval, R.attr.time_bar_scrubbing_enabled, R.attr.touch_target_height, R.attr.unplayed_color, R.attr.use_artwork, R.attr.use_controller, R.attr.vr_icon};
}
