package defpackage;

import java.util.Locale;
import java.util.function.Supplier;

/* JADX INFO: compiled from: r8-map-id-d258b9486bcf5759e155f5bab92d46ef62bd8d08e8b1f4ee09698e84cf22fec5 */
/* JADX INFO: loaded from: classes3.dex */
public final class si4 extends oe4 {
    public final dg2 l;
    public final Locale m;
    public final boolean n;
    public final String o;

    /* JADX INFO: compiled from: r8-map-id-d258b9486bcf5759e155f5bab92d46ef62bd8d08e8b1f4ee09698e84cf22fec5 */
    public static final class a {
        public String a;
        public String b;
        public boolean c;
        public mj0 d = mj0.PROGRESSIVE_HTTP;
        public dg2 e;
        public String f;
        public String g;
        public Boolean h;

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
        public si4 a() {
            String str;
            if (this.b == null) {
                e04.a("No valid content was specified. Please specify a valid one with setContent.");
                return null;
            }
            if (this.d == null) {
                e04.a("The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod.");
                return null;
            }
            String str2 = this.g;
            if (str2 == null) {
                e04.a("The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode.");
                return null;
            }
            if (this.h == null) {
                e04.a("The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated.");
                return null;
            }
            if (this.a == null) {
                dg2 dg2Var = this.e;
                if (dg2Var != null) {
                    str = "." + dg2Var.h;
                } else {
                    str = "";
                }
                this.a = str2 + str;
            }
            return new si4(this.a, this.b, this.c, this.e, this.d, this.g, this.h.booleanValue(), this.f);
        }

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
        public a b(boolean z) {
            this.h = Boolean.valueOf(z);
            return this;
        }

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
        public a c(String str, boolean z) {
            this.b = str;
            this.c = z;
            return this;
        }

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
        public a d(String str) {
            this.g = str;
            return this;
        }

        /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
        public a e(dg2 dg2Var) {
            this.e = dg2Var;
            return this;
        }
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    public si4(String str, String str2, boolean z, dg2 dg2Var, mj0 mj0Var, final String str3, boolean z2, String str4) {
        super(str, str2, z, dg2Var, mj0Var, str4);
        this.m = (Locale) iz1.a(str3).orElseThrow(new Supplier() { // from class: ri4
            /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
            @Override // java.util.function.Supplier
            public final Object get() {
                return si4.e(str3);
            }
        });
        this.o = str3;
        this.l = dg2Var;
        this.n = z2;
    }

    /* JADX DEBUG: Can't inline method, not implemented redirect type for insn: 0x0010: CONSTRUCTOR 
      (wrap:java.lang.String:STR_CONCAT ("not a valid locale language code: "), (r3v0 java.lang.String) A[MD:():java.lang.String (c), SYNTHETIC, WRAPPED] (LINE:13))
     A[MD:(java.lang.String):void (m)] (LINE:17) call: s83.<init>(java.lang.String):void type: CONSTRUCTOR */
    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    public static /* synthetic */ s83 e(String str) {
        return new s83("not a valid locale language code: " + str);
    }

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    @Override // defpackage.oe4
    public boolean b(oe4 oe4Var) {
        if (!super.b(oe4Var) || !(oe4Var instanceof si4)) {
            return false;
        }
        si4 si4Var = (si4) oe4Var;
        return this.o.equals(si4Var.o) && this.n == si4Var.n;
    }
}
